name: Check NixOS configs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check flake
        run: nix flake check --no-build

      - name: Evaluate t480
        run: nix eval .#nixosConfigurations.t480.config.system.build.toplevel.drvPath

      - name: Evaluate desktop
        run: nix eval .#nixosConfigurations.desktop.config.system.build.toplevel.drvPath

      - name: Evaluate server
        run: nix eval .#nixosConfigurations.server.config.system.build.toplevel.drvPath
